[project]
authors = ["Erik Tollerud <erik.tollerud@gmail.com>"]
channels = ["pytorch", "conda-forge"]
description = "Add a short description here"
name = "ml_generation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.1,<3"
scipy = ">=1.15.0,<2"
matplotlib = ">=3.9.1,<4"
jupyterlab = ">=4.3.4,<5"
tqdm = ">=4.67.1,<5"
ipywidgets = ">=8.1.5,<9"
astropy = ">=6.1.7,<7"
specutils = ">=1.19.0,<2"
torchvision = ">=0.20.1,<0.21"
ipykernel = ">=6.29.5,<7"
astroquery = ">=0.4.7,<0.5"
tensorboard = ">=2.18.0,<3"
graphviz = ">=7.1.0,<8"

[feature.cpu]
pypi-dependencies = { torch = ">=2.5.1,<3"}
#dependencies = {pytorch = ">=2.5.1,<3"}
pypi-options = { index-url = "https://download.pytorch.org/whl/cpu", extra-index-urls = ["https://pypi.org/simple"] }

[feature.cuda]
pypi-dependencies = { torch = ">=2.5.1,<3"}
#pypi-options = { index-url = "https://download.pytorch.org/whl/cu126", extra-index-urls = ["https://pypi.org/simple"] }
#channels = ["nvidia", {channel = "pytorch", priority = -1}]
#dependencies = {cuda = ">=12.1", pytorch-cuda = {version = "12.1.*", channel = "pytorch"}, pytorch = {version = ">=2.5.1,<3", channel = "pytorch"}}

[feature.rocm]
pypi-dependencies = { torch = ">=2.5.1,<3"}
pypi-options = { index-url = "https://download.pytorch.org/whl/rocm6.2", extra-index-urls = ["https://pypi.org/simple"] }

[environments]
default = ["cpu"] 
cuda = ["cuda"] 
rocm = ["rocm"] 

[pypi-dependencies]
sbi = { git = "https://github.com/sbi-dev/sbi.git" }
nflows = { git = "https://github.com/eteq/nflows.git" }
graphviz = ">=0.20.3, <0.21"

